# build web app
FROM node:23-slim AS builder
WORKDIR /app/front
COPY ./app/front .
RUN npm install
RUN npm run build

# nginx
FROM nginx:alpine
COPY ./nginx/ /etc/nginx/conf.d/
COPY --from=builder /app/front/dist /usr/share/nginx/html
